---

- name: Create NeoFS HTTP group
  ansible.builtin.group:
    name: '{{ neofs_http__group }}'
    system: yes

- name: Create NeoFS HTTP user
  ansible.builtin.user:
    name: '{{ neofs_http__user }}'
    group: '{{ neofs_http__group }}'
    password: '*'
    shell: '/usr/sbin/nologin'
    home: '{{ neofs_http__conf_dir }}'
    system: yes
    skeleton: no
