---

- name: Copy NeoFS HTTP wallet
  ansible.builtin.copy:
    content: "{{ neofs_http__wallet }}"
    dest: "{{ neofs_http__wallet_path }}"
    owner: 'root'
    group: "{{ neofs_http__group }}"
    mode: '0640'
